type: app
database: pg
language: ecr
model: clear

# list of tasks to be run by `amber watch`
watch:
  run:
    build_commands:
      - mkdir -p bin
      - crystal build ./src/chivi.cr -o bin/chivi-dev --error-trace
    run_commands:
      - bin/chivi-dev
    include:
      - ./config/**/*.cr
      - ./config/environments/*.yml
      - ./src/**/*.cr
    exclude:
      - ./src/cvmtl/**/*.cr
      - ./src/oldmt/**/*.cr
      - ./src/ysapp/**/*.cr

  spec:
    run_commands:
      - AMBER_ENV=test crystal spec
    include:
      - ./spec/engine/*.cr
