type: app
database: pg
language: ecr
model: clear

# list of tasks to be run by `amber watch`
watch:
  run:
    build_commands:
      - mkdir -p bin
      - crystal build ./src/webcv/webcv_srv.cr -o bin/cvapp-dev --error-trace
    run_commands:
      - bin/cvapp-dev
    include:
      - ./src/**/*.cr
    exclude:
      - ./src/cvmtl/**/*.cr
      - ./src/oldmt/**/*.cr
      - ./src/cvhlp/**/*.cr
      - ./src/ysapp/**/*.cr

  spec:
    run_commands:
      - AMBER_ENV=test crystal spec
    include:
      - ./spec/engine/*.cr
