type: app
database: pg
language: ecr
model: clear

# list of tasks to be run by `amber watch`
watch:
  run:
    build_commands:
      - crystal build ./src/webcv/webcv_srv.cr -o bin/cvapp-dev --error-trace
    run_commands:
      - bin/cvapp-dev
    include:
      - ./src/**/*.cr
    exclude:
      - ./src/cvmtl/**/*.cr
      - ./src/oldmt/**/*.cr
      - ./src/cvhlp/**/*.cr
      - ./src/ysapp/*.cr

  cvmtl:
    build_commands:
      - crystal build ./src/cvmtl/cvmtl_srv.cr -o bin/cvmtl-dev --error-trace
    run_commands:
      - bin/cvmtl-dev
    include:
      - ./src/cvmtl/**/*.cr

  # spec:
  #   run_commands:
  #     - CV_ENV=test crystal spec
  #   include:
  #     - ./spec/engine/*.cr
