time bin/zhinfo_seed hetushu -i 0
time bin/zhinfo_seed rengshu -i 0
time bin/zhinfo_seed xbiquge -i 0
time bin/zhinfo_seed biqugee -i 0
time bin/zhinfo_seed 69shu -i 0
time bin/zhinfo_seed 5200 -i 0
time bin/zhinfo_seed duokan8 -i 0
time bin/zhinfo_seed sdyfcm -i 0
time bin/zhinfo_seed biqu5200 -i 0
time bin/zhinfo_seed paoshu8 -i 0
time bin/zhinfo_seed bxwxorg -i 0
time bin/zhinfo_seed shubaow -i 0
time bin/zhinfo_seed jx_la -i 0
