ALTER TABLE btitles
  DROP COLUMN IF EXISTS vi_uc;

ALTER TABLE btitles
  DROP COLUMN IF EXISTS vi_qt;

ALTER TABLE btitles
  DROP COLUMN IF EXISTS vi_ms;

ALTER TABLE btitles
  DROP COLUMN IF EXISTS en_uc;
