- name: base
  cata: &base_cata
    c_id: /(\d+).html$/

- name: 69shu
  cata:
    <<: *base_cata
    link: https://www.69shu.com/%{b_id}/
    c_id: /(\d+)$/

- name: ptwxz
  cata:
    <<: *base_cata
    link: https://www.ptwxz.com/html/%{bdiv}/%{b_id}/index.html
