secret_key_base: E8yvjycoWdxVE72gcwAfbzf-6aVY0PJO2NAfvIwIzuo
port: 5010
name: chivi

logging:
  severity: debug
  colorize: true
  filter:
    - password
    - confirm_password

host: 0.0.0.0
port_reuse: true
process_count: 1
# ssl_key_file:
# ssl_cert_file:
database_url: postgres://postgres:postgres@localhost:5432/chivi_dev
auto_reload: true

session:
  key: chivi_sc
  store: signed_cookie
  expires: 2592000

smtp:
  enabled: false

pipes:
  static:
    headers:
      'Cache-Control': 'no-store'

secrets:
  description: Store your development secrets credentials and settings here.
