require "./con_parser"

TXT1 = <<-TXT
(TOP (IP (IP (NP-PN-SBJ (NR 路易斯·布努埃尔))
	  (VP (VC 是)
	      (NP-PRD (QP (CD 一)
			  (CLP (M 位)))
		      (NP-PN (NR 西班牙))
		      (NP (NN 超现实主义者)))))
      (PU ，)
      (IP (NP-SBJ (DNP (NP (PN 他))
		       (DEG 的))
		  (NP (NN 电影)))
	  (VP (VV 包括)
	      (UCP-OBJ (NP-PN (PU 《))
		       (NP (DNP (NP-PN (NR 安达鲁))
				(DEG 之))
			   (NP (NN 犬)))
		       (PU 》)
		       (PRN (PU （)
			    (IP (NP-LOC (NN 里面))
				(NP-SBJ-1 (NN 眼球))
				(VP (SB 被)
				    (VP (VV 割开)
					(NP-OBJ (-NONE- *-1)))))
			    (PU ）))
		       (PU 、)
		       (NP-PN (PU 《))
		       (NP (NN 黄金)
			   (NN 时代))
		       (PU 》)
		       (PU 、)
		       (NP-PN (PU 《))
		       (DNP (NP (NN 资产阶级))
			    (DEG 的))
		       (ADJP (JJ 审慎))
		       (NP (NN 魅力))
		       (PU 》)
		       (PU 、)
		       (NP-PN (PU 《))
		       (NN 女仆)
		       (NN 日记)
		       (PU 》)
		       (PU 、)
		       (NP-PN (PU 《))
		       (ADJP (JJ 毁灭))
		       (NP (NN 天使))
		       (PU 》)
		       (PU 、)
		       (NP-PN (PU 《))
		       (DNP (LCP (NP (NN 沙漠))
				 (LC 中))
			    (DEG 的))
		       (NP-PN (NR 西蒙))
		       (PU 》)
		       (CC 以及)
		       (NP (QP (CD 一)
			       (CLP (M 部)))
			   (DNP (PP (P 关于)
				    (NP (NP-PN (NR 基督))
					(NP (NN 一生))))
				(DEG 的))
			   (NP (NN 电影))))))
      (PU 。)
      (IP (LCP-LOC (NP (QP (DT 这)
			   (CLP (M 部)))
		       (NP (NN 电影)))
		   (LC 里))
	  (VP (VE 有)
	      (NP-OBJ (QP (CD 一)
			  (CLP (M 个)))
		      (DNP (ADJP (JJ 有趣))
			   (DEG 的))
		      (NP (NN 细节)))))
      (PU ，)
      (IP (NP-PN-SBJ (NR 基督))
	  (VP (VP (VSB (VV 跑步)
		       (VV 去)))
	      (VP (VV 听)
		  (NP-OBJ (DNP (NP (NN 山上))
			       (DEG 的))
			  (NP (NN 布道)))))
	  (PU ，)
	  (PP-PRP (P 因为)
		  (CP (IP (NP-SBJ (PN 他))
			  (VP (VV 迟到)))
		      (SP 了))))
      (PU 。)))
TXT

TXT2 = <<-TXT
(TOP (IP (NP-PN-SBJ (NR 布赖恩·Ｍ·帕普斯克))
      (VP (VV 撰写))))
TXT
pp AI::MtNode.from_str(TXT1)
